[package]
name = "azle_generate_rearchitecture"
version = "0.0.0"
edition = "2018"

[dependencies]
prettyplease = "0.2.12"
proc-macro2 = "1.0.66"
quote = "1.0.33"
serde = "1.0.183"
serde_json = "1.0.105"
swc_common = "0.31.21" # TODO why can't we get rid of this?
syn = "2.0.29"
