name: Azle Tests
on: [push]
jobs:
  basic-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      # - run: source /home/runner/.bashrc
      # - run: source /home/runner/.bash_profile
      # - run: export NVM_DIR="/home/runner/.nvm"
      # - run: source /home/runner/.nvm/nvm.sh
      # - run: \[ -s "$NVM_DIR/nvm.sh" \] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      # - run: \. "$NVM_DIR/nvm.sh"
      # - run: \[ -s "$NVM_DIR/bash_completion" \] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
      # - run: /home/runner/.nvm/nvm install 14
      # - run: source ~/.nvm/nvm.sh
      - run: export NVM_DIR="$HOME/.nvm"
      - run: \[ -s "$NVM_DIR/nvm.sh" \] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      - run: nvm install 14
      - run: nvm use 14
      - run: node --version
      # - run: npm --version
      # - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh


# - run: export NVM_DIR="$HOME/.nvm"
# - run: [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# - run: [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion